# data 관련 설정
image_root: /data/ephemeral/home/dong_yeong/data/cleansing_train/DCM
label_root: /data/ephemeral/home/dong_yeong/data/cleansing_train/outputs_json

# 모델명 및 사전 학습 여부
model_name: DeepLabV3Plus
model_parameter:
  encoder_name: xception
  classes: 29

# batch_size
train_batch_size: 4
val_batch_size: 4

# image resize
image_size: &image_size 512

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 1e-3
weight_decay: 1e-6

max_epoch: &max_epoch 30

# loss 관련 설정
loss_name: BCEWithLogitsLoss

# loss에 필요한 parameter -> dict 형태로 작성
loss_parameter: {}

# scheduler 관련 설정
scheduler_name: CosineAnnealingLR

# # reduce on placetu scheduler 필요한 parameter -> dict 형태로 작성 
# scheduler_parameter:
#   mode : min
#   patience : 5


# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter:
  T_max: *max_epoch
  eta_min: 1e-6

# random seed값
seed: 21

# validation 관련 인자
val_fold: 0
val_interval: 1
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/DeepLabV3Plus

# wandb
api_key: 67cf78f1678bcd1539448f4567d3b540efce7e03
team_name: ayeong-chonnam-national-university
project_name: Sementic Segmentation
experiment_detail: data_cleansing_test
