# data 관련 설정
image_root: /data/ephemeral/home/dong_yeong/data/train/DCM
label_root: /data/ephemeral/home/dong_yeong/data/train/outputs_json

# 모델명 및 사전 학습 여부
model_name: UnetPlusPlus
model_parameter:
  encoder_name: resnext101_32x8d
  encoder_weights : imagenet 
  classes: 29

# batch_size
train_batch_size: 2
val_batch_size: 1

# image resize
image_size: &image_size 512

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size
  # RandomBrightnessContrast:
  #   p: 0.5
  # CLAHE:
  #   clip_limit: 4.0
  #   tile_grid_size: [8, 8]
  #   p: 0.5
  # GaussianBlur:
  #   blur_limit: [3, 7]
  #   p: 0.5
  # MotionBlur:
  #   blur_limit: 3
  #   p: 0.5
  # RandomRotate90:
  #   p: 0.5
  HorizontalFlip:
    p: 0.5
  # ShiftScaleRotate:
  #   shift_limit: 0.0625
  #   scale_limit: 0.1
  #   rotate_limit: 45
  #   p: 0.5
  # ElasticTransform:
  #   alpha: 120
  #   sigma: 6
  #   p: 0.3
  # GridDistortion:
  #   p: 0.3
  # OpticalDistortion:
  #   distort_limit: 1
  #   shift_limit: 0.5
  # p: 0.3
  # CoarseDropout:
  #   max_holes: 8
  #   max_height: 32
  #   max_width: 32
  #   p: 0.3

# 학습 관련 하이퍼파라미터
lr: 1e-3
weight_decay: 1e-6

max_epoch: &max_epoch 100

# loss 관련 설정
loss_name: Focal_Dice_Loss

# loss에 필요한 parameter -> dict 형태로 작성
loss_parameter: {}

# scheduler 관련 설정
scheduler_name: reducelronplateau

# scheduler 필요한 parameter -> dict 형태로 작성 reduce on placetu
scheduler_parameter:
  mode : max
  patience : 16


# # scheduler 필요한 parameter -> dict 형태로 작성
# scheduler_parameter:
#   T_max: *max_epoch
#   eta_min: 1e-6

# random seed값
seed: 21

# validation 관련 인자
val_fold: 0
val_interval: 2
threshold: 0.5

# checkpoint 저장 경로
save_dir: ./checkpoints/UnetPlusPlus

# AMP 설정 추가
use_amp: False

# wandb
api_key: 67cf78f1678bcd1539448f4567d3b540efce7e03
team_name: ayeong-chonnam-national-university
project_name: Sementic Segmentation
experiment_detail: Unet++1024
