image_root: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/data/test/DCM

root_path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.4

model_paths:
  1024:
    model1:
      source: smp
      type: unetplusplus
      encoder: vgg19
      classes: 29
      path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/pretrained/UnetPlusPlus-vgg19-custom_aug-bce_dice-lion-cosine-1024-100ep.pt
    model2:
      source: smp
      type: unetplusplus
      encoder: tu-hrnet_w64
      classes: 29
      path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/pretrained/UnetPlusPlus-hrnet64-custom_aug-bce_dice-lion-plateau-1024-100ep.pt
    model3:
      source: smp
      type: unetplusplus
      encoder: efficientnet-b2
      classes: 30
      path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/pretrained/unet++effb2_9682.pt
    model4:
      source: smp
      type: deeplabv3plus
      encoder: tu-xception71
      classes: 30
      path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/pretrained/deeplabv3_xcept71_9679.pt
    model5:
      source: mmsegmentation
      type: segformer
      config: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/mmsegmentation/custom_config/segformer.py
      classes: 29
      path: /home/yehna/level2-cv-semanticsegmentation-cv-09-lv3/pretrained/segformer_iter_42000.pth

save_dir: ./soft_ensemble
output_name: output.csv